options:
  finder:
    - 'BASIC'
  
  parser:
    - 'NONE'
    - 'BASIC'
  
  FILLER:
    - 'FIXED'
    - 'RANDOM'
    - 'GPT3'
    - 'GPT3.5'
    - 'GPT4'
    - 'OTHER'

finder: 'BASIC'
parser: 'NONE'
filler: 'GPT3.5'