workflow:
  finder: 'QUERY'
  transformer: 'SIMPLIFY'
  parser: 'GPT3'
  filler: 'GPT3'

parameters:
  model: 'text-davinci-003'
  zero_shot: true
  temperature: 0.5
  max_tokens: 1024
  embedding_token_limit: 8191