models:
  fast_llm: 'gpt-3.5-turbo'
  smart_llm: 'gpt-4'
  embedding: 'text-embedding-ada-002'
  tokenizer: 'cl100k_base'

workflow:
  finder: 'BASIC'
  parser: 'NONE'
  filler: 'GPT3.5'

parameters:
  model: 'gpt-3.5-turbo'
  zero_shot: true
  temperature: 0.5
  embedding_token_limit: 8191